identity:
  name: list-datasets
  author: witmeng
  label:
    en_US: list datasets
    zh_Hans: 數據集列表
description:
  human:
    en_US: list dataset
    zh_Hans: 數據集列表
  llm: list dataset
parameters:
  - form: llm
    human_description:
      en_US: page number, default 1
      zh_Hans: 頁碼，默認1
    label:
      en_US: page
      zh_Hans: 頁碼
    llm_description: 頁碼
    name: page
    required: false
    type: number
  - form: llm
    human_description:
      en_US: page size, default 30
      zh_Hans: 每頁數據量，默認30
    label:
      en_US: pageSize
      zh_Hans: 頁數量
    llm_description: 每頁數據量，默認30
    name: pageSize
    required: false
    type: number      
extra:
  python:
    source: tools/list-datasets.py
